### ISSUE TITLE
Scrollview Not working inside Card

### ISSUE THREAD

**Issue by navi63** [yuyakaido/CardStackView#111]
Hi
thanks for this awesome code but I'm facing a problem i.e if there is any scrollview **inside** the card then cards are not able to swipe.if disable the scroll then cards works but how to use both scroll + swiping the cards?
please help

**Comment by Paridhi2502** [comment]
same problem happening in my code..any solution>?

**Comment by kolllor33** [comment]
Have you tried basing your code on this example? from here
I tested this with the newest version and it seems to work fine.

public ViewHolder(View itemView) {
            super(itemView);
            solutions = (TextView) itemView.findViewById(R.id.solutions);
            description = (TextView) itemView.findViewById(R.id.description);
            scrollable = (ScrollView) itemView.findViewById(R.id.childScroll);

            solutions.setOnTouchListener(new View.OnTouchListener() {

                public boolean onTouch(View v, MotionEvent event) {
                    // Disallow the touch request for parent scroll on touch of child view
                    v.getParent().requestDisallowInterceptTouchEvent(true);
                    return false;
                }
            });
}

**Comment by yuyakaido** [comment]
Duplication: https://github.com/yuyakaido/CardStackView/issues/105

**Comment by Rammohandubey1990** [comment]
Did you get any solution ?

**Comment by navneet-applify** [comment]
If someone still facing this issue in Aug 2020 then surely there is no improvement done in this code.

So solution to this problem exists. I did some coding and Jugaaad thing to get rid of this problem.

But now I don't have that code right now. but I can help 

You need to create an XML layout cell for the card and then in that cell you need to add again viewpager.

so what I'm saying you need a cell of view pager and attach to this library.

so now you have a viewpager of this library and in for each item, you have nested viewpager at each cell.

so now in nested view pager item you have to make new XML to reflect data and add scroll view as a parent of this item cell.

This will work.

And if you found any problem or problem with my English I can explain to you again because English is not my primary language.

**Comment by navi63** [comment]
If someone still facing this issue in Aug 2020 then surely there is no improvement done in this code.

So the solution to this problem exists. I did some coding and Jugaaad thing to get rid of this problem.

But now I don't have that code right now. but I can help 

You need to create an XML layout cell for the card and then in that cell, you need to add again view pager.

so what I'm saying you need a cell of view pager and attach to this library.

so now you have a view pager of this library and in for each item, you have nested view pager at each cell.

so now in nested view pager item, you have to make new XML to reflect data and add scroll view as a parent of this item cell.

This will work.

And if you found any problem or problem with my English I can explain to you again because English is not my primary language.
